// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: shared/proto/advisor.proto

package advisorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CityData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityData) Reset() {
	*x = CityData{}
	mi := &file_shared_proto_advisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityData) ProtoMessage() {}

func (x *CityData) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_advisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityData.ProtoReflect.Descriptor instead.
func (*CityData) Descriptor() ([]byte, []int) {
	return file_shared_proto_advisor_proto_rawDescGZIP(), []int{0}
}

func (x *CityData) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CityData) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CityData) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type AdvisorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cities        []*CityData            `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvisorRequest) Reset() {
	*x = AdvisorRequest{}
	mi := &file_shared_proto_advisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvisorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvisorRequest) ProtoMessage() {}

func (x *AdvisorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_advisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvisorRequest.ProtoReflect.Descriptor instead.
func (*AdvisorRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_advisor_proto_rawDescGZIP(), []int{1}
}

func (x *AdvisorRequest) GetCities() []*CityData {
	if x != nil {
		return x.Cities
	}
	return nil
}

type AdvisorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advice        string                 `protobuf:"bytes,1,opt,name=advice,proto3" json:"advice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvisorResponse) Reset() {
	*x = AdvisorResponse{}
	mi := &file_shared_proto_advisor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvisorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvisorResponse) ProtoMessage() {}

func (x *AdvisorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_advisor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvisorResponse.ProtoReflect.Descriptor instead.
func (*AdvisorResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_advisor_proto_rawDescGZIP(), []int{2}
}

func (x *AdvisorResponse) GetAdvice() string {
	if x != nil {
		return x.Advice
	}
	return ""
}

type StreamAdviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	IsComplete    bool                   `protobuf:"varint,2,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAdviceResponse) Reset() {
	*x = StreamAdviceResponse{}
	mi := &file_shared_proto_advisor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAdviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAdviceResponse) ProtoMessage() {}

func (x *StreamAdviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_advisor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAdviceResponse.ProtoReflect.Descriptor instead.
func (*StreamAdviceResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_advisor_proto_rawDescGZIP(), []int{3}
}

func (x *StreamAdviceResponse) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *StreamAdviceResponse) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

var File_shared_proto_advisor_proto protoreflect.FileDescriptor

const file_shared_proto_advisor_proto_rawDesc = "" +
	"\n" +
	"\x1ashared/proto/advisor.proto\x12\aadvisor\"V\n" +
	"\bCityData\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\";\n" +
	"\x0eAdvisorRequest\x12)\n" +
	"\x06cities\x18\x01 \x03(\v2\x11.advisor.CityDataR\x06cities\")\n" +
	"\x0fAdvisorResponse\x12\x16\n" +
	"\x06advice\x18\x01 \x01(\tR\x06advice\"M\n" +
	"\x14StreamAdviceResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\x12\x1f\n" +
	"\vis_complete\x18\x02 \x01(\bR\n" +
	"isComplete2\x9a\x01\n" +
	"\x0eAdvisorService\x12>\n" +
	"\tGetAdvice\x12\x17.advisor.AdvisorRequest\x1a\x18.advisor.AdvisorResponse\x12H\n" +
	"\fStreamAdvice\x12\x17.advisor.AdvisorRequest\x1a\x1d.advisor.StreamAdviceResponse0\x01B\x18Z\x16shared/proto/advisorpbb\x06proto3"

var (
	file_shared_proto_advisor_proto_rawDescOnce sync.Once
	file_shared_proto_advisor_proto_rawDescData []byte
)

func file_shared_proto_advisor_proto_rawDescGZIP() []byte {
	file_shared_proto_advisor_proto_rawDescOnce.Do(func() {
		file_shared_proto_advisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_advisor_proto_rawDesc), len(file_shared_proto_advisor_proto_rawDesc)))
	})
	return file_shared_proto_advisor_proto_rawDescData
}

var file_shared_proto_advisor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_proto_advisor_proto_goTypes = []any{
	(*CityData)(nil),             // 0: advisor.CityData
	(*AdvisorRequest)(nil),       // 1: advisor.AdvisorRequest
	(*AdvisorResponse)(nil),      // 2: advisor.AdvisorResponse
	(*StreamAdviceResponse)(nil), // 3: advisor.StreamAdviceResponse
}
var file_shared_proto_advisor_proto_depIdxs = []int32{
	0, // 0: advisor.AdvisorRequest.cities:type_name -> advisor.CityData
	1, // 1: advisor.AdvisorService.GetAdvice:input_type -> advisor.AdvisorRequest
	1, // 2: advisor.AdvisorService.StreamAdvice:input_type -> advisor.AdvisorRequest
	2, // 3: advisor.AdvisorService.GetAdvice:output_type -> advisor.AdvisorResponse
	3, // 4: advisor.AdvisorService.StreamAdvice:output_type -> advisor.StreamAdviceResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_proto_advisor_proto_init() }
func file_shared_proto_advisor_proto_init() {
	if File_shared_proto_advisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_advisor_proto_rawDesc), len(file_shared_proto_advisor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_advisor_proto_goTypes,
		DependencyIndexes: file_shared_proto_advisor_proto_depIdxs,
		MessageInfos:      file_shared_proto_advisor_proto_msgTypes,
	}.Build()
	File_shared_proto_advisor_proto = out.File
	file_shared_proto_advisor_proto_goTypes = nil
	file_shared_proto_advisor_proto_depIdxs = nil
}
