// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: shared/proto/weather.proto

package weatherpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherRequest) Reset() {
	*x = WeatherRequest{}
	mi := &file_shared_proto_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherRequest) ProtoMessage() {}

func (x *WeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherRequest.ProtoReflect.Descriptor instead.
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_weather_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *WeatherRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type WeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	FeelsLike     float64                `protobuf:"fixed64,4,opt,name=feels_like,json=feelsLike,proto3" json:"feels_like,omitempty"`
	TempMin       float64                `protobuf:"fixed64,5,opt,name=temp_min,json=tempMin,proto3" json:"temp_min,omitempty"`
	TempMax       float64                `protobuf:"fixed64,6,opt,name=temp_max,json=tempMax,proto3" json:"temp_max,omitempty"`
	Pressure      int32                  `protobuf:"varint,7,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Humidity      int32                  `protobuf:"varint,8,opt,name=humidity,proto3" json:"humidity,omitempty"`
	WindSpeed     float64                `protobuf:"fixed64,9,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	WindDeg       int32                  `protobuf:"varint,10,opt,name=wind_deg,json=windDeg,proto3" json:"wind_deg,omitempty"`
	Timestamp     int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherResponse) Reset() {
	*x = WeatherResponse{}
	mi := &file_shared_proto_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherResponse) ProtoMessage() {}

func (x *WeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherResponse.ProtoReflect.Descriptor instead.
func (*WeatherResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_weather_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *WeatherResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WeatherResponse) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *WeatherResponse) GetFeelsLike() float64 {
	if x != nil {
		return x.FeelsLike
	}
	return 0
}

func (x *WeatherResponse) GetTempMin() float64 {
	if x != nil {
		return x.TempMin
	}
	return 0
}

func (x *WeatherResponse) GetTempMax() float64 {
	if x != nil {
		return x.TempMax
	}
	return 0
}

func (x *WeatherResponse) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *WeatherResponse) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *WeatherResponse) GetWindSpeed() float64 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *WeatherResponse) GetWindDeg() int32 {
	if x != nil {
		return x.WindDeg
	}
	return 0
}

func (x *WeatherResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_shared_proto_weather_proto protoreflect.FileDescriptor

const file_shared_proto_weather_proto_rawDesc = "" +
	"\n" +
	"\x1ashared/proto/weather.proto\x12\aweather\"J\n" +
	"\x0eWeatherRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\xd6\x02\n" +
	"\x0fWeatherResponse\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"feels_like\x18\x04 \x01(\x01R\tfeelsLike\x12\x19\n" +
	"\btemp_min\x18\x05 \x01(\x01R\atempMin\x12\x19\n" +
	"\btemp_max\x18\x06 \x01(\x01R\atempMax\x12\x1a\n" +
	"\bpressure\x18\a \x01(\x05R\bpressure\x12\x1a\n" +
	"\bhumidity\x18\b \x01(\x05R\bhumidity\x12\x1d\n" +
	"\n" +
	"wind_speed\x18\t \x01(\x01R\twindSpeed\x12\x19\n" +
	"\bwind_deg\x18\n" +
	" \x01(\x05R\awindDeg\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp2X\n" +
	"\x0eWeatherService\x12F\n" +
	"\x11GetCurrentWeather\x12\x17.weather.WeatherRequest\x1a\x18.weather.WeatherResponseB\x18Z\x16shared/proto/weatherpbb\x06proto3"

var (
	file_shared_proto_weather_proto_rawDescOnce sync.Once
	file_shared_proto_weather_proto_rawDescData []byte
)

func file_shared_proto_weather_proto_rawDescGZIP() []byte {
	file_shared_proto_weather_proto_rawDescOnce.Do(func() {
		file_shared_proto_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_weather_proto_rawDesc), len(file_shared_proto_weather_proto_rawDesc)))
	})
	return file_shared_proto_weather_proto_rawDescData
}

var file_shared_proto_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_weather_proto_goTypes = []any{
	(*WeatherRequest)(nil),  // 0: weather.WeatherRequest
	(*WeatherResponse)(nil), // 1: weather.WeatherResponse
}
var file_shared_proto_weather_proto_depIdxs = []int32{
	0, // 0: weather.WeatherService.GetCurrentWeather:input_type -> weather.WeatherRequest
	1, // 1: weather.WeatherService.GetCurrentWeather:output_type -> weather.WeatherResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_weather_proto_init() }
func file_shared_proto_weather_proto_init() {
	if File_shared_proto_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_weather_proto_rawDesc), len(file_shared_proto_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_weather_proto_goTypes,
		DependencyIndexes: file_shared_proto_weather_proto_depIdxs,
		MessageInfos:      file_shared_proto_weather_proto_msgTypes,
	}.Build()
	File_shared_proto_weather_proto = out.File
	file_shared_proto_weather_proto_goTypes = nil
	file_shared_proto_weather_proto_depIdxs = nil
}
